const productos = [
    {
        id: 1,
        nombre: "3 en 1",
        precio: 3000,
        img: "../fotos/3en1.jpeg",
        cantidad: 1,
    },
    {
        id: 2,
        nombre: "Auto",
        precio: 1500,
        img: "../fotos/auto.jpg",
        cantidad: 1,
    },
    {
        id: 3,
        nombre: "Autos",
        precio: 2500,
        img: "../fotos/autos.jpg",
        cantidad: 1,
    },
    {
        id: 4,
        nombre: "Caja",
        precio: 4000,
        img: "../fotos/caja.jpg",
        cantidad: 1,
    },
    {
        id: 5,
        nombre: "Camion-robot",
        precio: 3500,
        img: "../fotos/camionrobot.jpg",
        cantidad: 1,
    },
    {
        id: 6,
        nombre: "Formas Basicas",
        precio: 4000,
        img: "../fotos/formasbasicas.jpg",
        cantidad: 1,
    },
    {
        id: 7,
        nombre: "Grua",
        precio: 2000,
        img: "../fotos/grua.jpg",
        cantidad: 1,
    },
    {
        id: 8,
        nombre: "Remolque",
        precio: 3500,
        img: "../fotos/remolque.jpg",
        cantidad: 1,
    },
    ];